apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: nginx
      image: nginx:1.23.0
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html
  volumes:
    - name: nginx-data
      emptyDir: {}
