apiVersion: v1
kind: Pod
metadata:
  name: nginx-policy
  labels:
   app: nginx
   type: webserver
spec:
  containers:
    - name: container-write
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true;do date >> /var/tmp/index.html;sleep 10;exit 0;done"]
      volumeMounts:
        - name: share-volume
          mountPath: /var/tmp
    - name: container-serve
      image: nginx
      ports:
        - containerPort: 80
          name: http
          hostPort: 8090
          protocol: TCP
      volumeMounts:
        - name: share-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: share-volume
      emptyDir: {}
    restartPolicy: OnFailure
